/*
 * ChartPanel.java
 *
 * Created on Feb 23, 2010, 11:05:27 AM
 */
package org.mei.securesim.platform.core.charts.ui;

import java.awt.Rectangle;
import org.mei.securesim.platform.core.charts.core.XYLineChart;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JPanel;
import org.mei.securesim.platform.core.charts.IChartDisplay;

/**
 *
 * @author posilva
 */
public class ChartPanel extends JPanel implements IChartDisplay {
    public static final String CHART_NAME = "Energy Consumption Chart";
    public static final String X_LABEL = "Time(s)";
    public static final String Y_LABEL = "Energy Consumption(%)";
    private Graphics currentG;
    XYLineChart chart;
    public XYLineChart getChartObject() {
        return chart;
    }
    public ChartPanel() {
        initComponents();
        this.chart = new XYLineChart(CHART_NAME, 5.0, Y_LABEL, X_LABEL);
        this.chart.setSeriesLinesAndShapes(CHART_NAME, true, false);
        //chart.getSeries("Consumo de Energia").add(1, 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public Graphics getG() {
        return currentG;
    }

    @Override
    public void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        Image offscreen = createImage(getSize().width,getSize().height);
        currentG = offscreen.getGraphics();
        chart.displayOn(this);
        grphcs.drawImage(offscreen,0,0,this);
    }

    public void update() {
        revalidate();
        repaint();
    }

    public void updateChart(double x, double y) {
        chart.getSeries(CHART_NAME).add(x, y);
        updateUI();
    }

    public Rectangle getRectangle() {
        return getBounds();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
