/*
 *     Wireless Sensor Network Simulator
 *   The next generation for WSN Simulations
 */

/*
 * EnergyHeatMapFrame.java
 *
 * Created on Jan 24, 2011, 11:45:30 PM
 */
package org.wisenet.platform.test;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Collection;
import javax.swing.JFrame;
import org.wisenet.platform.utils.GUI_Utils;
import org.wisenet.platform.utils.PlatformUtils;

/**
 *
 * @author posilva
 */
public class EnergyHeatMapFrame extends JFrame {

    EnergyHeatMap energyHeatMap = new EnergyHeatMap();

    /** Creates new form EnergyHeatMapFrame */
    public EnergyHeatMapFrame() {
        initComponents();
        jScrollPane1.setViewportView(energyHeatMap);
        jScrollPane1.setAutoscrolls(true);
        setPreferredSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));

        GUI_Utils.centerOnScreen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setName("jToolBar1"); // NOI18N

        btnSave.setText("Export");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setName("btnSave"); // NOI18N
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String returnVal = PlatformUtils.selectImageFile2save(this);
        if (returnVal != null) {
            if (PlatformUtils.saveImageToFile(returnVal, EnergyHeatMap.getBackgroundImage())) {
                return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public void displayHeat(Collection collection) {
        energyHeatMap.paintHeat(collection);
        jScrollPane1.setPreferredSize(energyHeatMap.getSize());

    }

    public void loadImage(BufferedImage bufferedImage) throws IOException {
        energyHeatMap.loadImage(bufferedImage);
        repaint();
        energyHeatMap.repaint();

    }
}
