/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestFrame.java
 *
 * Created on 15/Jul/2010, 0:33:17
 */
package org.wisenet.platform.ui.frames;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author CIAdmin
 */
public class TestFrame extends javax.swing.JFrame {

    static TestFrame instance;

    public static TestFrame getInstance() {
        initInstance();
        return instance;
    }

    public static TestFrame getInstance(String title) {
        initInstance();
        instance.setTitle(title);
        return instance;
    }

    private static void initInstance() {
        if (instance == null) {
            instance = new TestFrame();
        }
    }

    /** Creates new form TestFrame */
    public TestFrame() {
        initComponents();
    }

    public void addContentPanel(JPanel panel) {
        add(panel, BorderLayout.CENTER);
        setPreferredSize(panel.getPreferredSize());
        setMaximumSize(panel.getMaximumSize());
        setMinimumSize(panel.getMinimumSize());
        pack();
    }

    public void test() {
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
