/*
 **  Wireless Sensor Network Simulator
 *  The next generation for WSN Simulations
 */

/*
 * PlatformPanel.java
 *
 * Created on Sep 5, 2010, 1:11:04 AM
 */
package org.wisenet.platform.common.ui;

/**
 *
 * @author Pedro Marques da Silva <MSc Student @di.fct.unl.pt>
 */
public abstract class PlatformPanel extends javax.swing.JPanel {

    protected Object result = null;
    private IPlatformDialogActions notificationHandler;
    protected int minHeight = 600;
    protected int minWidth = 800;

    public Object getResult() {
        return result;
    }

    /** Creates new form PlatformPanel */
    public PlatformPanel() {
        initComponents();
    }

    public void setNotificationHandler(IPlatformDialogActions handler) {
        this.notificationHandler = handler;
    }

    /**
     * 
     */
    protected void notifyChanges() {
        if (notificationHandler != null) {
            notificationHandler.changesOccurred();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public abstract boolean onCancel();

    public abstract boolean onOK();

    public abstract boolean onApply();

    protected abstract boolean isDataValid();

    public boolean changed() {
        return false;
    }

    public int getMinWidth() {
        return minWidth;
    }

    public int getMinHeight() {
        return minHeight;
    }

    public void beforeStart(){
        
    }
    public abstract void beforeClose();
}
