/*
 * SimChartPanel.java
 *
 * Created on Feb 23, 2010, 11:05:27 AM
 */
package pt.unl.fct.di.mei.securesim.platform.charts;

import java.awt.Graphics;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author posilva
 */
public class SimChartPanel extends ChartPanel implements IChartDisplay {

    private Graphics currentG;
    XYLineChart chartObject;

    public XYLineChart getChartObject() {
        return chartObject;
    }


    public SimChartPanel(JFreeChart chart) {
        super(chart);
        initComponents();
        chartObject = new XYLineChart("Consumo de Energia", 5.0, "Energia consumida(%)", "Tempo(s)");
        chartObject.setYRange(false, 0, 100);
        chartObject.setSeriesLinesAndShapes("Consumo de Energia", true, false);
        setChart(chartObject.chart);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void displayOn(IChartDisplayable canvas) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Graphics getG() {
        return currentG;
    }

    @Override
    public void paintComponents(Graphics grphcs) {
        super.paintComponents(grphcs);
        currentG = grphcs;
        chartObject.displayOn(this);
        System.out.println("Painting");
    }

    public void update() {
        //
    }

    public void updateChart(double x, double y) {
        chartObject.getSeries("Consumo de Energia").add(x, y);
        updateUI();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
