/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OutputPanel.java
 *
 * Created on 13/Jul/2010, 22:25:05
 */
package org.mei.securesim.platform.ui.panels;

import javax.swing.JFrame;

/**
 *
 * @author CIAdmin
 */
public class OutputPanel extends SingletonPanel {

    /** Creates new form OutputPanel */
    public OutputPanel() {
        super();
        hasInstance = true;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public static OutputPanel getInstance() {
        if (instance == null) {
            instance = new OutputPanel();
        }
        return (OutputPanel) instance;
    }

    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.add(OutputPanel.getInstance());
        f.pack();
        f.setVisible(true);
    }
}
