/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulationPropertiesPanel.java
 *
 * Created on 14/Jul/2010, 9:54:56
 */
package org.wisenet.platform.ui.panels;

import org.jdesktop.application.Action;
import org.wisenet.platform.core.PlatformManager;
import org.wisenet.simulator.core.Simulator;

/**
 *
 * @author CIAdmin
 */
public class SimulationPropertiesPanel extends javax.swing.JPanel {

    /** Creates new form SimulationPropertiesPanel */
    public SimulationPropertiesPanel() {
        initComponents();
        loadSimulationSettings();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tgbFastMode = new javax.swing.JToggleButton();
        tgbRealTimeMode = new javax.swing.JToggleButton();
        titleArea = new javax.swing.JLabel();
        buttonArea = new javax.swing.JPanel();
        cmdCancel = new javax.swing.JButton();
        cmdOK = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.wisenet.platform.PlatformApp.class).getContext().getResourceMap(SimulationPropertiesPanel.class);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.wisenet.platform.PlatformApp.class).getContext().getActionMap(SimulationPropertiesPanel.class, this);
        tgbFastMode.setAction(actionMap.get("SetFastMode")); // NOI18N
        simulationMode.add(tgbFastMode);
        tgbFastMode.setSelected(true);
        tgbFastMode.setText(resourceMap.getString("tgbFastMode.text")); // NOI18N
        tgbFastMode.setName("tgbFastMode"); // NOI18N

        tgbRealTimeMode.setAction(actionMap.get("SetRealtimeMode")); // NOI18N
        simulationMode.add(tgbRealTimeMode);
        tgbRealTimeMode.setText(resourceMap.getString("tgbRealTimeMode.text")); // NOI18N
        tgbRealTimeMode.setName("tgbRealTimeMode"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgbFastMode, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(tgbRealTimeMode, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgbRealTimeMode)
                    .addComponent(tgbFastMode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        titleArea.setBackground(resourceMap.getColor("titleArea.background")); // NOI18N
        titleArea.setFont(resourceMap.getFont("titleArea.font")); // NOI18N
        titleArea.setText(resourceMap.getString("titleArea.text")); // NOI18N
        titleArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleArea.setMaximumSize(new java.awt.Dimension(200, 30));
        titleArea.setMinimumSize(new java.awt.Dimension(200, 30));
        titleArea.setName("titleArea"); // NOI18N
        titleArea.setOpaque(true);
        titleArea.setPreferredSize(new java.awt.Dimension(200, 40));
        add(titleArea, java.awt.BorderLayout.PAGE_START);

        buttonArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonArea.setMaximumSize(new java.awt.Dimension(32767, 40));
        buttonArea.setMinimumSize(new java.awt.Dimension(14, 40));
        buttonArea.setName("buttonArea"); // NOI18N
        buttonArea.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancel.setText(resourceMap.getString("cmdCancel.text")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N
        buttonArea.add(cmdCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        cmdOK.setText(resourceMap.getString("cmdOK.text")); // NOI18N
        cmdOK.setName("cmdOK"); // NOI18N
        buttonArea.add(cmdOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, -1));

        add(buttonArea, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void SetFastMode() {
        if (PlatformManager.getInstance().haveActiveSimulation()) {
            PlatformManager.getInstance().getActiveSimulation().getSimulator().setMode(Simulator.FAST);
        }
    }

    @Action
    public void SetRealtimeMode() {
        if (PlatformManager.getInstance().haveActiveSimulation()) {
            PlatformManager.getInstance().getActiveSimulation().getSimulator().setMode(Simulator.REAL);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonArea;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup simulationMode;
    private javax.swing.JToggleButton tgbFastMode;
    private javax.swing.JToggleButton tgbRealTimeMode;
    private javax.swing.JLabel titleArea;
    // End of variables declaration//GEN-END:variables

    private void loadSimulationSettings() {
        if (PlatformManager.getInstance().haveActiveSimulation()) {
            tgbFastMode.setSelected(PlatformManager.getInstance().getActiveSimulation().getSimulator().getMode() == Simulator.FAST);
            tgbRealTimeMode.setSelected(PlatformManager.getInstance().getActiveSimulation().getSimulator().getMode() == Simulator.REAL);
        }
    }
}
